name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        K8_CLUSTER_NAME: k8s-general
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show $K8_CLUSTER_NAME > $GITHUB_WORKSPACE/.kubeconfig
    - name: Run a one-line script
      run: ls -la
