name: Deploy

on:
  repository_dispatch:
    types: [deploy_apps]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        K8_CLUSTER_NAME: ${{ secrets.K8_CLUSTER_NAME }}
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show $K8_CLUSTER_NAME > $GITHUB_WORKSPACE/.kubeconfig
    - name: Run a one-line script
      run: ls -la