name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install node packages
      run: yarn install
      env:
        NODE_ENV: production
    - name: Build packages and modules
      run: yarn workspaces run build
      env:
        NODE_ENV: production
    - uses: actions/upload-artifact@v1
      with:
        name: api-artifact
        path: packages/api/index.js
