name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
    # TODO: testing
    - name: Trigger Module Publishing
      uses: octokit/request-action@v2.x
      id: dispatch_publish_modules
      with:
        route: POST /repos/:repository/dispatches
        repository: ${{ github.repository }}
        mediaType: '{"previews": ["everest"]}'
        event_type: "publish_modules"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
