name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Module Publishing
      uses: octokit/request-action@v2.x
      id: dispatch_publish_modules
      with:
        route: POST /repos/:repository/dispatches
        repository: ${{ github.repository }}
        mediaType: '{"previews": ["everest"]}'
        event_type: "publish_modules"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    # - name: Trigger Deployment
    #   run: |-
    #     curl
    #       -H "Accept: application/vnd.github.everest-preview+json" \
    #       -H "Authorization: token ${{secrets.GITHUB_ACCESS_TOKEN}}" \
    #       --request POST \
    #       --data '{"event_type": "publish_modules"}' \
    #       https://api.github.com/repos/Francois-Esquire/chelsea/dispatches
