name: Publish

on:
  repository_dispatch:
    types: [publish_modules]

jobs:
  publish_modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Remove Packages
      shell: bash
      run: rm -rf packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Modules
      env:
        NODE_ENV: development
      run: yarn
    - name: Build Modules
      env:
        NODE_ENV: production
        APP_URL: ${{ secrets.APP_URL }}
        CDN_URL: ${{ secrets.CDN_URL }}
      run: yarn workspaces run build
    - name: Publish Modules to Spaces
      env:
        NODE_ENV: production
        SPACES_ACCESS_KEY: ${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY }}
        SPACES_SECRET_KEY: ${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }}
        SPACES_BUCKET: ${{ secrets.DIGITALOCEAN_SPACES_BUCKET }}
        SPACES_ENDPOINT: ${{ secrets.DIGITALOCEAN_SPACES_ENDPOINT }}
        MODULES_ENDPOINT: ${{ secrets.MODULES_ENDPOINT }}
      run: yarn publish-modules
    - name: Trigger Image Publishing
      uses: octokit/request-action@v2.x
      id: dispatch_publish_docker_images
      with:
        route: POST /repos/:repository/dispatches
        repository: ${{ github.repository }}
        mediaType: '{"previews": ["everest"]}'
        event_type: "publish_docker_images"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
